export const CART_READ_REPOSITORY = 'CART_READ_REPOSITORY';
export const CART_WRITE_REPOSITORY = 'CART_WRITE_REPOSITORY';
export const CART_PRICING_SERVICE = 'CART_PRICING_SERVICE';


export default {
    CART_READ_REPOSITORY,
    CART_WRITE_REPOSITORY,
    CART_PRICING_SERVICE,
};
