// Tokens para inyección de dependencias en Inventory
export const INVENTORY_REPOSITORY = 'INVENTORY_REPOSITORY';
export const INVENTORY_WRITE_REPOSITORY = 'INVENTORY_WRITE_REPOSITORY';
export const INVENTORY_READ_REPOSITORY = 'INVENTORY_READ_REPOSITORY';
export const INVENTORY_PRODUCT_READONLY = 'INVENTORY_PRODUCT_READONLY';
export const INVENTORY_ORDER_READONLY = 'INVENTORY_ORDER_READONLY';

export default {
    INVENTORY_REPOSITORY,
    INVENTORY_WRITE_REPOSITORY,
    INVENTORY_READ_REPOSITORY,
    INVENTORY_PRODUCT_READONLY,
    INVENTORY_ORDER_READONLY,
};
