// Tokens de inyección para Order
export const ORDER_REPOSITORY = 'ORDER_REPOSITORY';
export const ORDER_CART_READONLY = 'ORDER_CART_READONLY';
export const ORDER_PRODUCT_READONLY = 'ORDER_PRODUCT_READONLY';
export const ORDER_PRICING_SERVICE = 'ORDER_PRICING_SERVICE';
export const ORDER_STOCK_SERVICE = 'ORDER_STOCK_SERVICE';

export default {
    ORDER_REPOSITORY,
    ORDER_CART_READONLY,
    ORDER_PRODUCT_READONLY,
    ORDER_PRICING_SERVICE,
    ORDER_STOCK_SERVICE,
};
