export const ADMIN_USER_READ = 'ADMIN_USER_READ';
export const ADMIN_PRODUCT_READ = 'ADMIN_PRODUCT_READ';
export const ADMIN_ORDER_READ = 'ADMIN_ORDER_READ';
export const ADMIN_PAYMENT_READ = 'ADMIN_PAYMENT_READ';
export const ADMIN_INVENTORY_READ = 'ADMIN_INVENTORY_READ';
export const ADMIN_PRODUCT_WRITE = 'ADMIN_PRODUCT_WRITE';
export const ADMIN_USER_WRITE = 'ADMIN_USER_WRITE';
export const ADMIN_ORDER_WRITE = 'ADMIN_ORDER_WRITE';
export const ADMIN_INVENTORY_WRITE = 'ADMIN_INVENTORY_WRITE';

export default {
    ADMIN_USER_READ,
    ADMIN_PRODUCT_READ,
    ADMIN_ORDER_READ,
    ADMIN_PAYMENT_READ,
    ADMIN_INVENTORY_READ,
    ADMIN_PRODUCT_WRITE,
    ADMIN_USER_WRITE,
    ADMIN_ORDER_WRITE,
    ADMIN_INVENTORY_WRITE,
};
